# ---------- STAGE 1: Build con Node ----------
FROM node:18-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# ---------- STAGE 2: Servir con Nginx ----------
FROM nginx:alpine

# Copiar tu config personalizada
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiar la carpeta build al servidor nginx
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 4028
CMD ["nginx", "-g", "daemon off;"]
